name: Update rapidhash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  update-header:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Download latest rapidhash.h
        run: |
          curl -o include/rapidhash.h https://raw.githubusercontent.com/Nicoshev/rapidhash/refs/heads/master/rapidhash.h

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update rapidhash.h from upstream"
          title: "Automatic update of rapidhash.h"
          body: | 
              This PR updates `rapidhash.h` with the latest version from the official repository.
              Source : [Nicoshev/rapidhash](https://github.com/Nicoshev/rapidhash)
          branch: auto-update/rapidhash
          delete-branch: true